// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
export var PurpleType;
(function (PurpleType) {
    PurpleType["SPChangeToken"] = "SP.ChangeToken";
    PurpleType["SPResourcePath"] = "SP.ResourcePath";
})(PurpleType || (PurpleType = {}));
export var Direction;
(function (Direction) {
    Direction["None"] = "none";
})(Direction || (Direction = {}));
export var ParentWebURL;
(function (ParentWebURL) {
    ParentWebURL["Empty"] = "/";
})(ParentWebURL || (ParentWebURL = {}));
export var FluffyType;
(function (FluffyType) {
    FluffyType["SPList"] = "SP.List";
})(FluffyType || (FluffyType = {}));
